package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
)

func run() error {
	app := NewApp()

	pflag.StringVarP(&app.systemDataFile, "system-data", "s", "", "system data file (generated by graphmaker)")
	pflag.StringSliceVarP(&app.fromSystems, "from-systems", "f", nil, "systems to start from")
	pflag.StringVarP(&app.toSystem, "to-system", "t", "", "system to go to")
	pflag.StringVarP(&app.toTag, "to-tag", "g", "", "tag to go to")
	pflag.StringSliceVarP(&app.avoidSystems, "avoid-systems", "i", nil, "systems to avoid")
	pflag.StringSliceVarP(&app.avoidTags, "avoid-tags", "j", nil, "tags to avoid")
	pflag.StringSliceVarP(&app.preferNotTags, "prefer-not", "p", nil, "tags to try and avoid")
	pflag.Parse()

	return app.Run()
}

func main() {
	if err := run(); err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	os.Exit(0)
}
