package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
)

func run() error {
	app := NewApp()

	pflag.StringVarP(&app.systemDataFile, "system-data", "s", "", "system data file (generated by graphmaker)")
	pflag.StringVarP(&app.listen, "listen", "l", ":8080", "hostport to listen on")
	pflag.Parse()

	if err := app.Prep(); err != nil {
		return err
	}

	return app.Serve()
}

func main() {
	if err := run(); err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	os.Exit(0)
}
